baseURL = "https://mitre-inspec.github.io/"
languageCode = "en-us"
title = "MITRE InSpec Compliance Framework"
theme = "devsec"
metaDataFormat = "yaml"

[[menu.global]]
  name = "Tools"
  weight = 2
  identifier = "inspec_tools"
  url = "/inspec_tools"

[[menu.global]]
  name = "Applications"
  weight = 3
  identifier = "application"
  url = "/application/"

[[menu.global]]
  name = "Baselines"
  weight = 4
  identifier = "baselines"
  url = "/baselines/"

[[menu.global]]
  name = "Community"
  weight = 6
  identifier = "comunity"
  url = "/community/"

[[menu.global]]
  name = "GitHub"
  weight = 8
  identifier = "github"
  url = "https://github.com/mitre/mitre-inspec.github.io"
