baseURL = "https://mitre-inspec.github.io/"
languageCode = "en-us"
title = "MITRE InSpec Compliance Framework"
theme = "devsec"
metaDataFormat = "yaml"

[[menu.main]]
  name = "Inspec tools"
  weight = 1
  identifier = "inspec_tools"
  url = "/inspec_tools"

[[menu.main]]
  name = "Heimdall Tools"
  weight = 2
  identifier = "heimdall_tools"
  url = "/heimdall_tools"

[[menu.main]]
  name = "Vulcan"
  weight = 3
  identifier = "vulcan"
  url = "/vulcan"

[[menu.main]]
  name = "Heimdall"
  weight = 4
  identifier = "heimdall"
  url = "/heimdall"

[[menu.main]]
  name = "Baselines"
  weight = 5
  identifier = "baselines"
  url = "/baselines"

[[menu.main]]
  name = "Community"
  weight = 6
  identifier = "comunity"
  url = "/community"

[[menu.main]]
  name = "GitHub"
  weight = 7
  identifier = "github"
  url = "https://github.com/mitre/mitre-inspec.github.io"
